### ISSUE TITLE
Enable usage of Flyway

### ISSUE THREAD

**Issue by serban-petrescu** [serban-petrescu/candidate-management#40]
- Investigate a little on [flyway](https://flywaydb.org).
- Read about [spring-flyway integration](https://docs.spring.io/spring-boot/docs/current/reference/html/howto-database-initialization.html#howto-execute-flyway-database-migrations-on-startup)
- Disable the hibernate auto ddl generation
- Move all table definitions inside a file (V1)
- See if we can easily move the CSV loading. If not, make another mock data SQL file with https://www.mockaroo.com/. This should run as a repeatable task (R__ file prefix).

**Comment by LorenaLore** [comment]
Appendix for all spring-boot properties: https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html

 Search for flyway to see all available properties to be set.
